version: '2'
services:
  webserver:
    build: ./simple-app
    restart: always
    privileged: true
  wifi-connect:
    build: ./wifi-connect
    network_mode: "host"
    labels:
      io.balena.features.dbus: '1'
    cap_add:
      - NET_ADMIN
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
  camera_test:
    build: ./camera-test
    privileged: true  # Allow access to the USB camera
    ports:
      - "8080:8080"
    devices:
      - "/dev/video0:/dev/video0"  # USB camera device
